- README.md
- src/bin/seq.rs
I'm pretty new to Rust, but I thought this would be a fun way to contribute to an interesting project.
If I'm doing anything that isn't idiomatic or that's just plain ugly, feel free to let me know and I'll change it!
> Adding seq to coreutils and updated README to reflect the changes.

- src/bin/ls.rs
- src/bin/rm.rs
it can be retrieved from history
> remove commented clap code from rm and ls

- src/bin/pwd.rs
The program currently isn't printing a newline at the end when it should be.
> Fix Missing Newline

- Cargo.toml
- src/bin/basename.rs
This program should be 100% feature complete.
> Add Basename

- Cargo.toml
- README.md
- src/bin/test.rs
This will add the test command to our list of provided utilities, which is almost feature complete. It's simply missing a few flag parameters that I wasn't sure how to implement right now and the ability to evaluate multiple expressions via parentheses. The `MAN_PAGE` variable only contains the features that I have implemented.
> Add Test Command

- src/bin/test.rs
This will return status codes in every function rather than calling exit immediately, allowing the program to call exit once at the end of the program and serving as prep work for implementing the ability to evaluate multiple expressions.
In addition, I've added some tests for test.
> Test: Return Status Codes & Add Tests

- src/bin/cat.rs
- Implemented all flag arguments except -v, as I literally have no idea what -v does.
> Improve cat Command

- src/bin/date.rs
- src/bin/time.rs
I saw that the man pages for the `date` and `time` commands weren't done, so I decided to do them. Any issues please mention.
> Date and Time man pages

- src/bin/rm.rs
This implementation never used the walkdir crate so it should be compatible with Redox.
> Improve Implementation of Remove

- src/bin/ls.rs
> Long format

- src/bin/sleep.rs
> Fix weird behavior with negative time intervals

- src/bin/date.rs
Fixes #73
Timezones are still TODO
> Format times

- src/bin/ls.rs
- src/lib.rs
The commit messages speak for themselves
> Finally implemented our homebrewed Arg Parser as a getopts substitute

- src/bin/wc.rs
- src/lib.rs
Fixed a bug as well. :sunglasses:
> Apply ArgParser to the `wc` command and refactor

- src/bin/cp.rs
@ticki, I need some peer review.
> Adapt cp.rs to ArgParser and fix behavior to POSIX specification

- Cargo.toml
- README.md
- src/bin/sort.rs
Here's my attempt at implementing `sort`. Hopefully it's close to what you are looking for.
fixes #79
> New util - sort

- src/bin/clear.rs
- src/bin/cp.rs
- src/bin/date.rs
- src/bin/env.rs
- src/bin/free.rs
- src/bin/ls.rs
- src/bin/mkdir.rs
- src/bin/mv.rs
- src/bin/ps.rs
- src/bin/sleep.rs
- src/bin/sort.rs
- src/bin/tee.rs
- src/bin/time.rs
- src/bin/touch.rs
- src/bin/wc.rs
- src/bin/yes.rs
- src/lib.rs
I want some peer review before feeling comfortable to merge.
> Revamping `ArgParser` with a new feature, better performance, and a cleaner API

- src/bin/basename.rs
- src/lib.rs
> More ArgParser changes review

- src/bin/df.rs
- src/bin/kill.rs
- src/bin/ls.rs
- src/lib.rs
Bins depending on syscall crate just display an error when run on linux
Fix usage of stderr in ls
Don't bind unused value in lib
> Fix build errors and warnings

- src/bin/tail.rs
> Need some review

- README.md
A few utilies were missing in the list of included utilities in the REAMDE.md file.
> Update the list of currently included utilities

- Cargo.toml
- src/bin/tr.rs
not a functional tr yet, only some option processing done
> adept pet project tr to redox coreutils

- src/bin/cut.rs
I've changed cut.rs so that it uses coreutils::ArgPaser.
> Adapt cut.rs to ArgParser

- src/bin/tr.rs
this has code from uutils/coreutils. It is copied because it needs work (which can then probably be given back)
> include range check and simple escapes

- src/bin/mkdir.rs
> mkdir add --parents option

- Cargo.toml
- src/bin/cp.rs
first feasibility reconnaissance
> introducing walkdir to solve #89

- src/bin/cat.rs
> cat: check if path is a folder

- src/bin/dd.rs
- if no input file is given, read from stdin
- if no output file is given, write to stdout
closes #126
> Add support for stdin and stdout for dd

- src/bin/mv.rs
no solution for cross filesystem moves yet.
fixes #89
> mv recursive

- src/bin/ls.rs
> add basic support for symbolic links to ls command

- Cargo.toml
- README.md
- src/bin/uniq.rs
Hi there,
Would you mind taking a look at what I've so far for the `uniq` command? 
I started off using the code from `sort`. The code from `repeated_lines` and `unique_lines` are based in the code from `std::vec:Vec::dedup_by`.
I'd love to get some feedback from more experienced Rust developers! 😃 
Thanks!
> [WIP] uniq command

- src/bin/ls.rs
> Change ls to use BufWriter

- src/lib.rs
fn format_time splitted into fn get_time_tuple and fn format_time. 
Preparing lib.rs for changes in https://github.com/n0npax/extrautils/tree/add-cal-to-extrautils
> function format_date splitted into 2 function + run rustfmt on file lib.rs

- src/bin/stat.rs
Depends on https://github.com/redox-os/syscall/pull/11.
> Use O_NOFOLLOW in stat

- src/bin/readlink.rs
- src/bin/stat.rs
It now works on Unix.
Depends on https://github.com/redox-os/rust/pull/10.
> Use libstd instead of syscall for stat

- Cargo.toml
- README.md
- src/bin/base64.rs
FreeBSD implementation was the one I liked the most!
> Added the 'base64' utility modeled after FreeBSD's one.

- Cargo.toml
- src/bin/uname.rs
Requires https://github.com/redox-os/kernel/pull/39.
> Add uname utility

- Cargo.toml
The new release works on Redox.
> Use released version of filetime

- src/bin/mv.rs
* Fixed an edge case where the user could try to copy a directory onto a file
* Restructured the code to remove an unnecessary if clause and some unnecessary checks, thus causing a tiny performance increase
* Cntrl-Alt-L
> Reformatted, Restructured, Fix few bugs

- src/bin/cp.rs
> Ported changes from mv.rs to cp.rs

- src/bin/dd.rs
Replaced unnecessary Input and Output structs by a Box<io::Read>
Signed-off-by: Jerome Jutteau <mojo@couak.net>
> Simplify dd

- src/bin/dd.rs
Signed-off-by: Jerome Jutteau <j.jutteau@gmail.com>
> dd: Fix status option

- Cargo.lock
- src/bin/stat.rs
Updates to `stat` post `rust_users` API updates.
CC: @MggMuggins
> Update to use new redox_users API
