redox-os/coreutils

- src/bin/echo.rs
Simple change to only accept the -n flag if it is the first argument, which as far as I could see I how most echo implementations does it including `tcsh`. Also some changes to how it is written out, to remove the trailing white space after the last argument.
> Only check for -n flag as first argument. Fix extra white space.

- src/bin/sleep.rs
With this patch, the sleep command will be able to process floating point numbers as input so that it will be possible to sleep for shorter time periods, such as 0.5 seconds. It will also be able to accept input with a human-readable suffix indicating the duration of time to sleep (s for seconds, m for minutes, h for hours and d for days). Finally, it will also be able to accept multiple input arguments, allowing sleep to sleep for the combined amount of time specified (will make more sense for why when given the following example). In addition, I've also replaced the deprecated code with the current standard.
- `sleep 60` is equivalent to `sleep 1m`
- `sleep 90` is equivalent to `sleep 1.5m` is equivalent to `sleep 1m 30s`
> Proposal: Improved Implementation of Sleep Command

- src/bin/basename.rs
- Remove all usage of the `println!` macro
- Add examples in the `MAN_PAGE`
- Improve descriptions in the `MAN_PAGE`
- Don't use a `String` for truncating the pathname in `basename()`
- Remove use of `unwrap()` in favour of an error message with `exit(1)`
- Fix lack of suffix detection when not using multiple mode
> Fix Issues With Basename

- Cargo.toml
- README.md
- src/bin/head.rs
- src/bin/tail.rs
Simple implementations of 'head' and 'tail' commands.
They support the -/+ prefixes for line/byte count, e.g. 'tail -n +10 <file>' prints all but the first 10 lines of the file.
Input files get loaded into memory (one by one), which should be fine for most use cases. This keeps the implementation simple, unlike for example FreeBSD's tail with over 1000 lines of code.
Edit: above is no longer true, it uses efficient implementations now, but doesn't implement the '-' prefix for 'head', e.g. 'head -n -10 <file>'.
> add head and tail commands

- src/bin/wc.rs
Example:
```
sachiel@jiyuu:[coreutils]$ ./target/debug/wc ~/matlab ~/meikle ~/slowcat
1683 6027 55331 /home/sachiel/matlab
1    1    25    /home/sachiel/meikle
12   44   274   /home/sachiel/slowcat
1696 6072 55630 total
sachiel@jiyuu:[coreutils]$ 
```
This closes #24.
> Make wc output for multiple files aligned

- Cargo.toml
- src/bin/cut.rs
All options are implemented except for `-n`
> Add cut command

- src/bin/cat.rs
- Added exit_status to the Program structure to keep track of errors.
- Removed the vector for buffering the file and instead opted for printing to stdout directly.
- Implemented caret (^) and M- notation for showing non-printable characters.
> Completed Implementation of Cat

- src/bin/cat.rs
Iterate over a file using BufReader's bytes() implementation over Files. This leads to a huge performance increase. This makes it almost identical to the C version's performance.
real: 727ms
user: 193ms
sys:   37ms
real: 1205ms
user:  240ms
sys:   467ms
> Increase Cat Performance With BufReader

- src/bin/basename.rs
- src/bin/cat.rs
- src/bin/cut.rs
- src/bin/tail.rs
- src/bin/test.rs
A simple assortment of fixes found by [clippy](https://github.com/Manishearth/rust-clippy). In addition to these fixes, there is also a fix for basename , cat and cut. For basename, std::process::exit() has a minor cosmetic change to rename it to process::exit(). For cat, the "-" path now works as an alias for stdin, and stdin now may be used with flag arguments. Finally, the tests for cut have been fixed.
> Clippy Fixes & Basename/Cat Fixes

- Cargo.toml
- src/bin/printenv.rs
You can use it like this:: 
```sh
$ printenv <variable_name>
```
> Add the printenv command

- src/bin/cat.rs
Supports writing arguments as -vET rather than -v -E -T.
> Better Argument Parsing for Cat

- src/bin/mkdir.rs
Hey,
My first attempt to contribute to this project! Saw the issue #19, thought it's a good starting point.
Didn't notice a consistent pattern for printing man pages (e.g. `test` prints with --help, `du` is not printing it but has `#![deny(warnings)]` comment out). Not sure if I missed one? So decided that --help option seems reasonable. Totally happy to change it if I missed some convention!
The build is passing here https://travis-ci.org/GedRap/coreutils/builds/130974461 .
Thanks.
> Implement man page for mkdir, print it when executing mkdir --help.

- src/bin/cp.rs
- src/bin/env.rs
- src/bin/mv.rs
- src/bin/pwd.rs
- src/bin/rm.rs
- src/bin/rmdir.rs
- src/bin/seq.rs
- src/bin/yes.rs
Added manual page to the following, which should close the issue #19:
- cp
- env
- mv
- pwd
- rmdir
- rm
- seq
- yes
All these tools print the man page when called with `-h` or `--help` operand.
It probably makes sense to squash the commits, committed separately just to make it easier to read.
> Add manual pages to the tools that were missing it.

- src/bin/clear.rs
- src/bin/cp.rs
- src/bin/date.rs
- src/bin/dmesg.rs
- src/bin/du.rs
- src/bin/echo.rs
- src/bin/free.rs
- src/bin/ls.rs
- src/bin/mkdir.rs
- src/bin/printenv.rs
- src/bin/ps.rs
- src/bin/realpath.rs
- src/bin/reset.rs
- src/bin/shutdown.rs
- src/bin/time.rs
- src/bin/touch.rs
Added help (`-h` and `--help`) flags to all coreutils that were missing them except `true` and `false` as well as updated all the man pages to fit the new functionality.
`#![deny(warings)]` was now reactivated as well for all altered files, as the unused `const` warning is no longer happening.
> Help Flags

- src/bin/ls.rs
Hi, I changed `ls.rs` to print in human readable sizes. The `to_human_readable_string` function can be reused in `du.rs`, but I don't want to just copy is there. Where is a good location to put `to_human_readable_string`?
fixes #76
> Human readable sizes WIP

- src/bin/ls.rs
Some code reorganizing.
Support for the `--human-readable` flag.
Support for parsing single char flags with one dash, so you can do:
```
> ls -lh
> ls -hl
```
etc.
> Enhance `ls` some more

- src/lib.rs
Long opts were incorrectly matching on `Some` in the hashmap, and not removing the `=` from the value.
Short opts were not properly consuming the rest of the argument as the option's argument.
Adds handling of`--` to stop parsing of args.
> Argument parsing fixes and features

- src/bin/cut.rs
> Allow multibyte character as field delimiter

- src/bin/sleep.rs
sleep.rs parses it's arguments and waits the according time sequentially, in a way that if an invalid time interval appears after valid time intervals, it errors out during execution.
For exemple, currently, the command
sleep 1m redox 30s
will wait 1 minute then exit with an error saying 'redox' is not a valid interval.
This PR makes it so sleep.rs parses all it's arguments first, errors out if needed, and only then starts waiting.
> Preparse the arguments to error out early when needed

- Cargo.toml
- README.md
- src/bin/which.rs
One of the first things I do when popping in a foreign shell is finding where binaries are installed. For this reason, I decided to add this.
```
ion:file:/home/user# which man ls rg
file:/bin/man
file:/bin/ls
rg not found
```
> Adds a 'which' command

- src/bin/dd.rs
- src/lib.rs
`dd` now adheres to ArgParser. All core utilities should now use ArgParser.
More work needs to be done to address #126.
> Makes dd use ArgParser

- Cargo.toml
- src/bin/date.rs
- src/bin/ls.rs
- src/lib.rs
fix some rustfmt issues in file ls.rst
fix fail when symlink is broken (will print info now)
add showing symbolic link destination (-l)
add possibilities to show date of:
* modification [--modified-date] (-l)
* access [--accessed-date]
* creation [--created-date]
> Add new flags and functionality to ls command

- Cargo.toml
- README.md
- src/bin/ln.rs
add basic ln command to the coreutils
ln supports symbolic links, hard links and force params
modification of mk (mk/userspace/coreutils.mk) in separate PR directly to redox repo
> Add ln command to coreutils

- src/bin/sort.rs
While working on a `unique` command, I noticed that `sort` was missing the `--unique` option. So I thought it'd be a nice first contribution. :)
> Add --unique option to sort

- src/bin/tail.rs
Adds -f and -F to tail, which allow following the content of a file. Also adds -s to configure how often the utility should check for changes in files.
Also fixed a 'bug' where a newline would be printed when the last line of a file did not end with a newline.
I'd love some feedback!
Note: following files works on Linux, but not on Redox; it seems the seek() function on Redox isn't fully implemented (it seemed like it always returned 0, instead of what it should).
> Add -f and -F to tail

- src/bin/uniq.rs
* Avoid heap allocations when comparing case-insensitively;
* Write bytes directly to stdout, without converting to strings. The only exception is the counter for the `-c` option that is passed in as a `fmt::Arguments` to avoid using an external crate (itoa or numtoa).
> Performance improvements for uniq

- src/bin/wc.rs
- testing/multi_line_lang_file
In order to support the Unicode Derived Core Property `White_Space` when
counting words, this change iterates over chars instead of bytes.
Otherwise, for instance, if a file containing the Greek letter `ς`
(`U+03C2`) is being iterated over as bytes the second byte of that
letter will get recognized as `U+00A0 (NBSP)` and therefore `wc` will
return wrong count of words.
A test file with several lines, different kind of spaces, a lot of
Unicode symbols for different languages and of course an emoji is also
added to confirm a correct behavior, which might be useful for other
utils when it comes to testing correct Unicode support.
> Consider Unicode spaces when counting words

- Cargo.toml
- README.md
- src/bin/uptime.rs
It only shows the uptime. Based on the `screenfetch` implementation.
Right now that code is duplicated but we could replace the code of `screenfetch` by interpolating the output of this one? Just an idea.
In the future we might add load average, user counts and all the other things the other `uptime` do.
> Added 'uptime' command.

- Cargo.toml
I was trying to build Redox with latest coreutils and complains about @ids1024 fork not existing and I remembered that filetime Redox support just got merged.
> Mainstream filetime can be used now.

- src/bin/uptime.rs
Just small tweak. As  @nrobinaubertin pointed out that remainder is not needed as we don't show years. Good catch!
> We don't show years. Removing remainder in the days calculation.

- src/bin/df.rs
This fixes build when cross-compiling which happened to be broken when I removed a unused import. 
Basically the CI compiles using the host compiler and not the Redox cross-compiled one.
> Fix broken compilation on Redox.

- Cargo.lock
- Cargo.toml
- src/bin/stat.rs
- src/bin/tee.rs
Details:
- Using `redox_users` instead of `useutils`.
- Updated dependencies.
- Fixed some warnings in `tee`.
- Fixed formatting in `stat`.
> Migrated to `redox_users`.

- src/bin/cat.rs
std::io::copy() has a tendency to be slow (most likely because its streamed), so adding an additional function that simply reads into a buffer then outputs it gives a relatively significant performance boost. 
Of course, usually the speed of cat isn't something that is important, but this lets the coreutils beat gnu-coreutils (around 2.4-2.6 GB/s on my machine) and may improve quality of life for people that use cat to copy files for some reason.
When using flags, cat still has a tendency to be ridiculously slow (116 MB/s on my machine vs 685 MB/s for gnu-cat), but it still is an improvement compared to how it was before (58 MB/s).
Testing was done on an Intel m3-6Y30 using `cat /dev/zero | pipebench -q > /dev/null`
> Performance improvement for cat without arguments
